services:
  openconnect:
    image: ghcr.io/jimyag/openconnect:latest
    container_name: openconnect
    restart: always
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - MKNOD
    devices:
      - /dev/net/tun
    ports:
      - 53200:53200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://xxx"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
