services:
  openconnect:
    image: ghcr.io/jimyag/openconnect:latest
    container_name: openconnect
    restart: always
    privileged: true
    environment:
      - LDAP_USER=admin
      - LDAP_PASSWD=123456
      - VPN_SERVER=test.abc.com
      - GOST_PORT=53200
    ports:
      - 53200:53200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:53200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
