services:
  derper:
    container_name: derper
    image: ghcr.io/jimyag/derper:latest
    environment:
      - HOSTNAME=derper.your-domain.com
      - VERIFY_CLIENTS=true
    ports:
      - "80:80"
      - "443:443"
      - "3478:3478/udp"
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock